### ISSUE TITLE
Enter windows directory after Audi command?

### ISSUE THREAD

**Issue by Jniosi0291** [newtonsart/win-password-recovery#1]

**Comment by Jniosi0291** [comment]
Sudo command*

**Comment by newtonsart** [comment]
You need to mount the drive with windows in it.
You can follow the steps on the following link for learning how to mount it [https://www.tecmint.com/mount-windows-partition-in-ubuntu/](https://www.tecmint.com/mount-windows-partition-in-ubuntu/)
